### ISSUE TITLE
[English support]: Login does not work 

### ISSUE THREAD

**Issue by mordoth94** [pangolp/support#11] opened 2021-05-19 17:55 UTC
# Wow-CMS English support

### What operating system are you using?
- [x] Windows

### What version of PHP do you use?
- [x] PHP 7.x

### Where did you get the CMS code?
- [x] Github

### Where are you trying to install the CMS?
- [x] Dedicated server

### Which emulator are you using and which version?
- [x] TrinityCore

### Describe the bug
- I can't login through the Website. But ingame there is no problem, so it seems to be an CMS sided problem. 
May the encryption but I don't know. 
The only thing I know, it works with the old blizzcms. I just try cause I have the old files. 

### How can I reproduce the problem?

1. Compile with https://github.com/conan513/SingleCore_TC
2. Try to set up a site for this core 

### Screenshots
Table Structure FROM accounts
![IMG_20210514_204208_edit_27870718946267](https://user-images.githubusercontent.com/20024965/118860668-f7d1c300-b8db-11eb-8e5b-bd362b6ef49e.jpg)

**Comment by pangolp** [comment] 2021-05-19 18:02
Did you select SRP6 or Old Trinity during installation?

**Comment by mordoth94** [comment] 2021-05-19 18:13
I already try any option just to see it work.

**Comment by pangolp** [comment] 2021-05-20 00:03
Did it work for you?

**Comment by mordoth94** [comment] 2021-05-20 00:37
No.
The only way for me is to work with the BlizCMS Plus from 2years ago 🙈

But this shouldnt be the solution.

**Comment by pangolp** [comment] 2021-05-20 00:41
Are you Pepe? A, I didn't know. I don't recognize you with that username. It should work. The problem is that I don't have such an old version of the emulator to test. I'll try to see if I can reproduce the problem.

**Comment by sayghteight** [comment] 2021-05-21 15:11
Segun me ha comentado por Privado, se soluciono con el siguiente commit  https://github.com/WoW-CMS/BlizzCMS/commit/52c3b36de8666c32c824c9ff078d9c68d0f9c7cc .

I close the Issue.

**Closed** 2021-05-23 14:10 UTC
Labels: English
